<?php 

include "header.phtml";

?>

<div class="row marketing">

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Message</th>
                <th>Info</th>
            </tr>
        </thead>
        <tbody>
            
            <?php foreach($entries as $entry): ?>
                <tr>
                    <td><?= $entry->msg ?></td>
                    <td><?= $entry->created_at ?></td>
                </tr>
            <?php endforeach; ?>
            
        </tbody>
    </table>

</div>

<?php

include "footer.phtml";

?>